//                                                  || जय श्री राम ||
//                                            विजेतव्या लङ्का चरणतरणीयो जलनिधिः
//                                            विपक्षः पौलस्त्यो रणभुवि सहायाश्च कपयः।
//                                              तथाप्येको रामः सकलमवधीद्राक्षसकुलं
//                                             क्रियासिद्धिः सत्त्वे भवति महतां नोपकरणे॥

//                                    vijetavyā laṅkā caraṇataraṇīyo jalanidhiḥ
//                                  vipakṣaḥ paulastyo raṇabhuvi sahāyāśca kapayaḥ।
//                                    tathāpyeko rāmaḥ sakalamavadhīdrākṣasakulaṃ
//                                   kriyāsiddhiḥ sattve bhavati mahatāṃ nopakaraṇe॥

//                               For winning over Laṅkā, Shree Ram had to walk across the sea. 
//                  Ravana was powerful; and Shree Ram's army was of Vanaras (all odds were against Shree Ram). 
//                                       Inspite of that, Ram killed all the demons. 
//                                Success of a person depends solely on their own capacities.

//                                Source – Subhāṣitaratnabhāṇḍāgāram, Sajjanapraśaṃsā 250

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import collagePic from "@/assets/collage.jpg";
import background from "@/assets/bg.svg";
import Router from 'next/router'
import backgroundImg from "@/assets/background";
import Card from 'react-bootstrap/Card';
// import logo from "@/assets/lo";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        <title>
          Tailwind Starter Template - App Landing Page Template: Tailwind
          Toolbox
        </title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link
          rel="stylesheet"
          href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
        />
        {/*Replace with your tailwind.css once created*/}
        <link
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700"
          rel="stylesheet"
        />
        {/* Animation CSS*/}
        <style
          dangerouslySetInnerHTML={{
            __html:
              "\t\t\n\t\t /* ----------------------------------------------\n\t\t * Generated by Animista\n\t\t * w: http://animista.net, t: @cssanimista\n\t\t * ---------------------------------------------- */\n\t\t \n\t\t.slide-in-bottom{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) both}\n\t\t.slide-in-bottom-h1{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .5s both}\n\t\t.slide-in-bottom-subtitle{-webkit-animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both;animation:slide-in-bottom .5s cubic-bezier(.25,.46,.45,.94) .75s both}\n\t\t.fade-in{-webkit-animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both;animation:fade-in 1.2s cubic-bezier(.39,.575,.565,1.000) 1s both}\n\t\t.bounce-top-icons{-webkit-animation:bounce-top .9s 1s both;animation:bounce-top .9s 1s both}\n\t\t\n\t\t@-webkit-keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}@keyframes slide-in-bottom{0%{-webkit-transform:translateY(1000px);transform:translateY(1000px);opacity:0}100%{-webkit-transform:translateY(0);transform:translateY(0);opacity:1}}\n\t\t@-webkit-keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}@keyframes bounce-top{0%{-webkit-transform:translateY(-45px);transform:translateY(-45px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in;opacity:1}24%{opacity:1}40%{-webkit-transform:translateY(-24px);transform:translateY(-24px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}65%{-webkit-transform:translateY(-12px);transform:translateY(-12px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}82%{-webkit-transform:translateY(-6px);transform:translateY(-6px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}93%{-webkit-transform:translateY(-4px);transform:translateY(-4px);-webkit-animation-timing-function:ease-in;animation-timing-function:ease-in}25%,55%,75%,87%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out}100%{-webkit-transform:translateY(0);transform:translateY(0);-webkit-animation-timing-function:ease-out;animation-timing-function:ease-out;opacity:1}}\n\t\t@-webkit-keyframes fade-in{0%{opacity:0}100%{opacity:1}}@keyframes fade-in{0%{opacity:0}100%{opacity:1}}\n\t\t\t\t\n\t",
          }}
        />
        <div
          // style={{ backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' version='1.1' xmlns:xlink='http://www.w3.org/1999/xlink' xmlns:svgjs='http://svgjs.com/svgjs' width='1440' height='560' preserveAspectRatio='none' viewBox='0 0 1440 560'%3e%3cg mask='url(%26quot%3b%23SvgjsMask1011%26quot%3b)' fill='none'%3e%3crect width='1440' height='560' x='0' y='0' fill='rgba(162%2c 207%2c 255%2c 0.53)'%3e%3c/rect%3e%3cpath d='M0%2c645.897C118.633%2c639.209%2c188.928%2c513.665%2c290.689%2c452.321C396.537%2c388.513%2c551.237%2c387.338%2c609.621%2c278.404C667.94%2c169.591%2c626.978%2c30.113%2c577.626%2c-83.05C534.611%2c-181.682%2c424.276%2c-225.26%2c354.312%2c-307.013C283.731%2c-389.487%2c258.778%2c-508.488%2c165.714%2c-564.371C61.505%2c-626.947%2c-72.171%2c-675.528%2c-185.289%2c-631.035C-298.239%2c-586.609%2c-332.275%2c-446.492%2c-396.236%2c-343.34C-449.765%2c-257.012%2c-507.081%2c-175.213%2c-529.375%2c-76.113C-553.053%2c29.142%2c-566.495%2c140.323%2c-527.687%2c240.987C-487.752%2c344.575%2c-400.62%2c418.742%2c-312.543%2c486.326C-217.823%2c559.007%2c-119.203%2c652.617%2c0%2c645.897' fill='rgba(83%2c 166%2c 255%2c 0.53)'%3e%3c/path%3e%3cpath d='M1440 1034.2559999999999C1534.716 1021.677 1633.924 1038.0720000000001 1717.643 992.0219999999999 1804.277 944.369 1859.94 859.7570000000001 1911.0819999999999 775.136 1967.866 681.178 2055.395 581.978 2030.007 475.17 2004.45 367.654 1854.6019999999999 346.619 1788.221 258.265 1713.98 159.449 1736.616-15.36099999999999 1623.702-65.63 1514.134-114.40999999999997 1393.725-17.587999999999965 1285.714 34.54899999999998 1192.777 79.40899999999999 1109.808 137.339 1042.017 215.14600000000002 974.077 293.124 911.883 379.58799999999997 896.044 481.791 880.118 584.554 918.707 684.113 954.192 781.861 992.521 887.446 1010.861 1020.867 1110.538 1072.653 1210.679 1124.6799999999998 1328.132 1049.113 1440 1034.2559999999999' fill='rgba(241%2c 248%2c 255%2c 0.53)'%3e%3c/path%3e%3c/g%3e%3cdefs%3e%3cmask id='SvgjsMask1011'%3e%3crect width='1440' height='560' fill='white'%3e%3c/rect%3e%3c/mask%3e%3c/defs%3e%3c/svg%3e")` }}

          style={{overflow : "scroll", height : "100vh"}} className={styles.srcollbar}
        >
         
              {/* <p className="leading-normal text-base md:text-2xl mb-2 text-center md:text-left slide-in-bottom-h1" style={{textAlign :"right",fontSize : "18px", color : "#fff"}}>
                <b>The Government Polytechnic, Nagpur is an autonomous educational institution of the government of Maharashtra, a state in Western India</b> 
              </p> */}
              <Image 
                src={require('@/assets/WhatsApp Image 2023-04-03 at 8.16.02 PM.jpeg')}
                width={'100%'}
                height={'100%'}
                style={{margin: "auto"}}
                className="slide-in-bottom-h1"
              />
               <h1 className="my-4 text-3xl md:text-5xl font-bold leading-tight text-center md:text-left slide-in-bottom-h1 " style={{color : "#fff", paddingTop : "3vh"}} >
                Welcome to Pariksha
              </h1>
            {/*Left Col*/}
            
            <Card className="slide-in-bottom-subtitle" style={{textAlign : "center",justifyContent : "center", padding : "40px", alignItems : "center", width : "600px", margin : "auto", marginTop : "60px"}}>
              
              <p className="leading-normal text-base md:text-2xl mb-2 text-center md:text-left slide-in-bottom-subtitle" style={{textAlign :"right",fontSize : "18px"}}>
                <b>Developed by :</b> <br/>
                Tanishka Badnaware (2007006)  <br/>
                Vaishnavi Dhore (2007019) <br/>
                Kanishka katekhaye (2007031) <br/>
                Tanishka Yewale (2007067) <br/>
              </p>
              <p className="leading-normal text-base md:text-2xl mb-8 text-center md:text-left slide-in-bottom-subtitle" style={{textAlign :"right",fontSize : "18px"}}>
              <b>Guide : </b>
                Dr. A. R. Mahajan <br/>
              <b>Co-Guide : </b>
                Priti Saktel
              </p>
              
              </Card>
              <div className=" slide-in-bottom-subtitle" style={{textAlign : "center", margin : "auto", marginTop : "50px", marginBottom : "50px"}}>
                <div className={styles.LoginButtonContainer} style={{textAlign : "center", margin : "auto"}}>
                  <div className={styles.LoginButton} style={{textAlign : "center",margin : "auto"}} onClick={() => Router.push('/select')}>
                      <p className={styles.LoginButtonText}>{`Join to PARIKSHA`}</p>
                  </div>
                </div>
              </div>
          </div>
          
      </>
    </>
  );
}
